import { Router, type Request, type Response } from "express";
import { prisma } from "../db/client";
import { requireAuth } from "../middleware/auth";

const router = Router();

router.use(requireAuth);

/**
 * GET /api/agents/:id/report
 * Generates and downloads a comprehensive markdown evaluation report for the agent.
 */
router.get("/agents/:id/report", async (req: Request, res: Response): Promise<void> => {
  try {
    const id = req.params.id as string;

    const agent = await prisma.agent.findUnique({
      where: { id },
      include: {
        versions: {
          orderBy: { version: "desc" },
          include: {
            runs: {
              where: { status: "COMPLETED" },
              include: {
                scenario: true,
                classification: true,
              },
            },
          },
        },
      },
    });

    if (!agent || agent.versions.length === 0) {
      res.status(404).json({ error: "Agent not found" });
      return;
    }

    const latestVersion = agent.versions[0];
    const runs = latestVersion.runs;

    const passedRuns = runs.filter((r) => r.classification?.passFail === "pass");
    const failedRuns = runs.filter((r) => r.classification?.passFail === "fail");
    const totalRuns = runs.length;
    const reliabilityScore = totalRuns > 0 ? ((passedRuns.length / totalRuns) * 100).toFixed(1) : "0.0";

    const failureCounts: Record<string, number> = {
      tool_loop: 0,
      hallucinated_confidence: 0,
      unsafe_destructive_action: 0,
      goal_drift: 0,
    };

    for (const r of failedRuns) {
      const type = r.classification?.failureType || "unknown";
      if (type in failureCounts) {
        failureCounts[type] = (failureCounts[type] || 0) + 1;
      }
    }

    // Build formatted Markdown report
    const markdown = `# Sentinel AI — Agent Reliability & Evaluation Report

**Generated:** ${new Date().toUTCString()}  
**Agent:** ${agent.name} (\`${agent.id}\`)  
**Domain:** ${agent.domain}  
**Active Version:** v${latestVersion.version}  
**Model Config:** ${latestVersion.model} (temp: ${latestVersion.temperature})

---

## 1. Executive Summary

- **Overall Reliability Score:** **${reliabilityScore}%**
- **Total Scenarios Evaluated:** ${totalRuns}
- **Passed Scenarios:** ${passedRuns.length}
- **Failed Scenarios:** ${failedRuns.length}

---

## 2. Failure Mode Taxonomy Breakdown

| Failure Taxonomy Category | Count | % of Total Failures | Status |
|---|---|---|---|
| 🔄 **Tool Loop** | ${failureCounts.tool_loop} | ${failedRuns.length > 0 ? Math.round((failureCounts.tool_loop / failedRuns.length) * 100) : 0}% | ${failureCounts.tool_loop === 0 ? "✅ Clear" : "⚠️ Detected"} |
| 🎭 **Hallucinated Confidence** | ${failureCounts.hallucinated_confidence} | ${failedRuns.length > 0 ? Math.round((failureCounts.hallucinated_confidence / failedRuns.length) * 100) : 0}% | ${failureCounts.hallucinated_confidence === 0 ? "✅ Clear" : "⚠️ Detected"} |
| 🛑 **Unsafe Destructive Action** | ${failureCounts.unsafe_destructive_action} | ${failedRuns.length > 0 ? Math.round((failureCounts.unsafe_destructive_action / failedRuns.length) * 100) : 0}% | ${failureCounts.unsafe_destructive_action === 0 ? "✅ Safe" : "🚨 Action Required"} |
| 🧭 **Goal Drift** | ${failureCounts.goal_drift} | ${failedRuns.length > 0 ? Math.round((failureCounts.goal_drift / failedRuns.length) * 100) : 0}% | ${failureCounts.goal_drift === 0 ? "✅ Clear" : "⚠️ Detected"} |

---

## 3. Sample Failure Case Studies

${
  failedRuns.length === 0
    ? "*Zero failures detected in the active evaluation suite. All scenarios passed expected behaviors.*"
    : failedRuns
        .slice(0, 5)
        .map(
          (r, idx) => `
### Case ${idx + 1}: ${r.scenario.category.toUpperCase()} — \`${r.classification?.failureType}\`
- **Scenario Prompt:** """${r.scenario.prompt}"""
- **Target Risk Type:** \`${r.scenario.riskType}\`
- **Expected Behavior:** ${r.scenario.expectedBehavior}
- **Judge Confidence:** ${((r.classification?.confidence || 0) * 100).toFixed(0)}%
- **Judge Reasoning:**
  > ${r.classification?.reasoning || "No reasoning captured"}
`
        )
        .join("\n")
}

---

## 4. Version History & Regression Tracking

| Version | Total Runs | Passed | Failed | Reliability % | Created At |
|---|---|---|---|---|---|
${agent.versions
  .map((v) => {
    const vPassed = v.runs.filter((r) => r.classification?.passFail === "pass").length;
    const vFailed = v.runs.filter((r) => r.classification?.passFail === "fail").length;
    const vTotal = v.runs.length;
    const vScore = vTotal > 0 ? ((vPassed / vTotal) * 100).toFixed(1) : "0.0";
    return `| v${v.version} | ${vTotal} | ${vPassed} | ${vFailed} | **${vScore}%** | ${v.createdAt.toISOString().split("T")[0]} |`;
  })
  .join("\n")}

---

*Report automatically generated by Sentinel AI Evaluation Engine.*
`;

    res.setHeader("Content-Type", "text/markdown; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="${agent.name.toLowerCase().replace(/\s+/g, "_")}_evaluation_report.md"`);
    res.send(markdown);
  } catch (error) {
    console.error(`[Reports] GET /api/agents/${req.params.id}/report failed:`, error);
    res.status(500).json({ error: "Failed to generate report", message: error instanceof Error ? error.message : String(error) });
  }
});

export default router;
